import { writeFile } from "node:fs/promises";
import { Events } from "discord.js";
import { createDiscordClient } from "@/core/client.ts";
import { ENV } from "@/core/config.ts";

const outputPath = new URL("../shared/emojis/emojis.generated.d.ts", import.meta.url);
const toTypeLiteral = (value: string) => JSON.stringify(value);
const client = createDiscordClient();

client.once(Events.ClientReady, async () => {
  try {
    const emojis = await client.application?.emojis.fetch();
    if (!emojis) {
      throw new Error("Impossible de récupérer les emojis de l'application.");
    }

    const entries = [...emojis.values()]
      .filter((emoji): emoji is typeof emoji & { name: string } => emoji.name !== null)
      .sort((a, b) => a.name.localeCompare(b.name));
    const emojiTypes = entries
      .map(
        (emoji) =>
          `  | { readonly name: ${toTypeLiteral(emoji.name)}; readonly id: ${toTypeLiteral(emoji.id)} }`,
      )
      .join("\n");
    const source = `// Generated by src/scripts/generate-emojis.ts — do not edit.\n\ndeclare type ApplicationEmoji =\n${emojiTypes || "  never"};\n\ndeclare type EmojiName = ApplicationEmoji["name"];\ndeclare type EmojiId = ApplicationEmoji["id"];\ndeclare type EmojiIdForName<Name extends EmojiName> = Extract<ApplicationEmoji, { name: Name }>["id"];\ndeclare type EmojiNameForId<Id extends EmojiId> = Extract<ApplicationEmoji, { id: Id }>["name"];\n`;

    await writeFile(outputPath, source, "utf8");
    console.log(`[Emojis] ${entries.length} types generated.`);
  } finally {
    client.destroy();
  }
});

await client.login(ENV.DISCORD_TOKEN);
